[package]
name = "anet-ebpf"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
aya-ebpf = "0.2.1"
aya-log-ebpf = "0.2.0"
anet-ebpf-common = { path = "../anet-ebpf-common" }

[[bin]]
name = "anet-ebpf"
path = "src/main.rs"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
debug = false
