//! Универсальный менеджер DNS
//! Поддерживает Linux (resolvectl, nmcli), macOS (scutil) и Windows (netsh).

use anyhow::Result;
#[cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))]
use log::{info, warn};
#[cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))]
use anyhow::Context;
use std::net::Ipv4Addr;

#[cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))]
use std::process::Command;

#[cfg(target_os = "macos")]
use std::io::Write;

#[cfg(target_os = "macos")]
use log::debug;
#[cfg(target_os = "windows")]
use std::os::windows::process::CommandExt;
#[cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))]
use std::process::Stdio;
#[cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))]
use std::string::ToString;
#[cfg(target_os = "linux")]
use std::fs;
#[cfg(target_os = "linux")]
use std::path::Path;
#[cfg(target_os = "linux")]
use std::sync::Mutex;

/// Трейт для управления DNS
pub trait DnsManager: Send + Sync {
    /// Установить DNS серверы для указанного интерфейса
    fn set_dns(&self, interface_name: &str, servers: &[Ipv4Addr]) -> Result<()>;
    /// Восстановить (сбросить) настройки DNS
    fn restore_dns(&self, interface_name: &str) -> Result<()>;
}

/// Фабрика для получения менеджера под текущую ОС
pub fn get_dns_manager() -> Box<dyn DnsManager> {
    #[cfg(target_os = "linux")]
    return Box::new(LinuxDnsManager::new());

    #[cfg(target_os = "macos")]
    return Box::new(MacOSDnsManager);

    #[cfg(target_os = "windows")]
    return Box::new(WindowsDnsManager);

    #[cfg(not(any(target_os = "linux", target_os = "macos", target_os = "windows")))]
    return Box::new(NoOpDnsManager);
}

// --- LINUX IMPLEMENTATION ---
#[cfg(target_os = "linux")]
pub struct LinuxDnsManager {
    resolv_conf_path: String ,
    backup_path: String,
    original_content: Mutex<Option<String>>,
}
#[cfg(target_os = "linux")]
impl  LinuxDnsManager {
    fn new() -> Self {
        Self{
            resolv_conf_path:  "/etc/resolv.conf".to_string(),
            backup_path: "/etc/resolv.conf.anet-backup".to_string(),
            original_content: Mutex::new(None),
        }
    }

    fn build_resolv_conf(servers: &Vec<String>) -> String {
        let mut content = String::from("# Generated by ANet VPN\n");
        for server in servers {
            content.push_str(&format!("nameserver {}\n", server));
        }
        content
    }
}
#[cfg(target_os = "linux")]
impl DnsManager for LinuxDnsManager {

    fn set_dns(&self, iface: &str, dns: &[Ipv4Addr]) -> Result<()> {
        if dns.is_empty() {
            return Ok(());
        }

        let dns_strings: Vec<String> = dns.iter().map(|ip| ip.to_string()).collect();
        info!("Configuring DNS for interface '{}'. Servers: {:?}", iface, dns_strings);

        if is_command_available("resolvectl") {
            info!("Strategy 1: Trying 'resolvectl'...");

            let mut args = vec!["dns", iface];
            for d in &dns_strings {
                args.push(d);
            }

            let output = Command::new("resolvectl")
                .args(&args)
                .output();

            match output {
                Ok(out) if out.status.success() => {
                    info!("Success: DNS set via resolvectl.");

                    // Дополнительно: настраиваем домен поиска (~.), чтобы systemd-resolved
                    // приоритетно отправлял DNS-запросы в этот интерфейс.
                    // Это важно для предотвращения DNS Leak.
                    let _ = Command::new("resolvectl")
                        .args(&["domain", iface, "~."])
                        .output();

                    return Ok(());
                }
                Ok(out) => {
                    // Утилита есть, но вернула ошибку (например, сервис выключен, как у тебя в Manjaro)
                    let err = String::from_utf8_lossy(&out.stderr);
                    warn!("Strategy 1 failed: resolvectl returned error: {}", err.trim());
                    // Не выходим, идем к следующей стратегии
                }
                Err(e) => {
                    warn!("Strategy 1 failed: Failed to execute resolvectl: {}", e);
                }
            }
        } else {
            info!("Strategy 1 skipped: 'resolvectl' not found.");
        }

        info!("Try change DNS from conf file {}", self.resolv_conf_path);
        let original =
            fs::read_to_string(self.resolv_conf_path.clone());

        let original = match original {
            Ok(content) => {content}
            Err(e) => {
                warn!("Cannot read {} {}", self.resolv_conf_path, e);
                return Ok(());
            }
        };

        {
            let mut guard = self.original_content.lock().unwrap();
            *guard = Some(original.clone());
        }

        // Also write backup to disk in case process crashes
        if let Err(e) = fs::write(self.backup_path.clone(), &original) {
            warn!("Failed to write backup file: {}", e);
        }

        // Write new resolv.conf
        let new_content = Self::build_resolv_conf(&dns_strings);
        match fs::write(self.resolv_conf_path.clone(), &new_content) {
            Ok(_) => {
                info!("Successfully wrote DNS to {}", self.resolv_conf_path);
                return Ok(());
            }
            Err(e) => {warn!("Cannot write DNS to {}: {}", self.resolv_conf_path, e);}
        }

        warn!("ALL DNS STRATEGIES FAILED. Please configure DNS manually for '{}'.", iface);
        Ok(())
    }


   fn restore_dns(&self, iface: &str) -> Result<()> {
        info!("Restoring DNS configuration for '{}'...", iface);

        // Пытаемся откатить changes во всех системах, так как мы не храним состояние,
        // какой именно метод сработал.

        // 1. Revert systemd-resolved
        if is_command_available("resolvectl") {
            let _ = Command::new("resolvectl").args(&["revert", iface]).output();
        }

        // 2. resolv.conf
       let original = {
           let mut guard = self.original_content.lock().unwrap();
           guard.take()
       };

       match original {
           Some(content) => {
               info!("Restoring original DNS configuration...");
               fs::write(self.resolv_conf_path.clone(), &content)
                   .context("Failed to restore /etc/resolv.conf")?;

               // Remove backup file
               let _ = fs::remove_file(self.backup_path.clone());

               info!("DNS configuration restored");
               return Ok(());
           }
           None => {
               // Try to restore from backup file if in-memory backup is missing
               if Path::new(&self.backup_path.clone()).exists() {
                   info!("Restoring DNS from backup file...");
                   let backup =
                       fs::read_to_string(self.backup_path.clone()).context("Failed to read backup file")?;
                   fs::write(self.resolv_conf_path.clone(), &backup)
                       .context("Failed to restore /etc/resolv.conf from backup")?;
                   let _ = fs::remove_file(self.backup_path.clone());
                   info!("DNS configuration restored from backup");
               } else {
                   warn!("No DNS backup found, nothing to restore");
               }
           }
       }

        Ok(())
    }
}

// Вспомогательная функция для проверки наличия утилиты в PATH
#[cfg(target_os = "linux")]
fn is_command_available(program: &str) -> bool {
    Command::new("which")
        .arg(program)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|status| status.success())
        .unwrap_or(false)
}

// --- MACOS IMPLEMENTATION ---
#[cfg(target_os = "macos")]
pub struct MacOSDnsManager;

#[cfg(target_os = "macos")]
impl MacOSDnsManager {
    const SERVICE_NAME: &'static str = "ANetVPN";

    fn run_scutil(commands: &str) -> Result<()> {
        debug!("Running scutil with commands:\n{}", commands);
        let mut child = Command::new("scutil")
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()?;

        if let Some(mut stdin) = child.stdin.take() {
            stdin.write_all(commands.as_bytes())?;
        }

        let output = child.wait_with_output()?;
        if !output.status.success() {
            warn!("scutil failed: {}", String::from_utf8_lossy(&output.stderr));
        }
        Ok(())
    }
}

#[cfg(target_os = "macos")]
impl DnsManager for MacOSDnsManager {
    fn set_dns(&self, _iface: &str, servers: &[Ipv4Addr]) -> Result<()> {
        // На macOS для utun интерфейсов имя интерфейса в scutil не используется напрямую
        // для глобального резолвинга, мы создаем "Сервис" в State:/Network/Service
        if servers.is_empty() { return Ok(()); }

        let server_list = servers.iter().map(|ip| ip.to_string()).collect::<Vec<_>>().join(" ");

        // ВАЖНО: Мы используем _iface только для логов, так как scutil работает с глобальным стейтом
        // или с ключом сервиса. Твой код использовал константу ANetVPN.

        let commands = format!(
            r#"d.init
d.add ServerAddresses * {servers}
d.add SupplementalMatchDomains * ""
set State:/Network/Service/{service}/DNS
"#,
            servers = server_list,
            service = Self::SERVICE_NAME
        );

        info!("Configuring DNS via scutil for macOS");
        Self::run_scutil(&commands)
    }

    fn restore_dns(&self, _iface: &str) -> Result<()> {
        info!("Restoring DNS on macOS...");
        let command = format!("remove State:/Network/Service/{}/DNS\n", Self::SERVICE_NAME);
        Self::run_scutil(&command)
    }
}

// --- WINDOWS IMPLEMENTATION ---
#[cfg(target_os = "windows")]
pub struct WindowsDnsManager;

#[cfg(target_os = "windows")]
impl DnsManager for WindowsDnsManager {
    fn set_dns(&self, iface: &str, servers: &[Ipv4Addr]) -> Result<()> {
        if servers.is_empty() { return Ok(()); }

        // В Windows имя интерфейса (iface) - это "Friendly Name" (например, "anet-client"),
        // которое мы задаем при создании адаптера Wintun.

        info!("Setting DNS via netsh for interface '{}': {:?}", iface, servers);

        for (i, ip) in servers.iter().enumerate() {
            let ip_str = ip.to_string();
            let index_arg = format!("index={}", i + 1);
            let args = if i == 0 {
                // Первый DNS: set dns
                vec!["interface", "ip", "set", "dns", iface, "static", &ip_str]
            } else {
                // Остальные: add dns
                vec!["interface", "ip", "add", "dns", iface, &ip_str, &index_arg]
            };

            Self::run_netsh(&args)?;
        }
        Ok(())
    }

    fn restore_dns(&self, iface: &str) -> Result<()> {
        // Сброс на DHCP (или очистка)
        info!("Restoring DNS for '{}' to DHCP", iface);
        let _ = Self::run_netsh(&["interface", "ip", "set", "dns", iface, "dhcp"]);
        Ok(())
    }
}

#[cfg(target_os = "windows")]
impl WindowsDnsManager {
    const CREATE_NO_WINDOW: u32 = 0x08000000;

    fn run_netsh(args: &[&str]) -> Result<()> {
        let output = Command::new("netsh")
            .args(args)
            .creation_flags(Self::CREATE_NO_WINDOW)
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .output()
            .context("Failed to run netsh")?;

        if !output.status.success() {
            let err = String::from_utf8_lossy(&output.stderr);
            // Игнорируем ошибки "объект уже существует" и подобные, если надо
            warn!("netsh warning/error: {}", err.trim());
        }
        Ok(())
    }
}

// --- NO-OP IMPLEMENTATION (Android / Unknown) ---
#[cfg(not(any(target_os = "linux", target_os = "macos", target_os = "windows")))]
pub struct NoOpDnsManager;

#[cfg(not(any(target_os = "linux", target_os = "macos", target_os = "windows")))]
impl DnsManager for NoOpDnsManager {
    fn set_dns(&self, _iface: &str, _servers: &[Ipv4Addr]) -> Result<()> { Ok(()) }
    fn restore_dns(&self, _iface: &str) -> Result<()> { Ok(()) }
}
