# Stage 1: Build static assets
FROM node:22-alpine AS builder
WORKDIR /app

# Копируем package.json из папки фронтенда
COPY anet-webui/package*.json ./
RUN npm ci

# Копируем весь исходный код фронтенда
COPY anet-webui/ .
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html

# Забираем конфиг Nginx из папки contrib
COPY contrib/config/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
