name: "Build Client"

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      - name: "Install Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"
          target: "x86_64-unknown-linux-gnu"
          override: "true"

      - name: "Build (Linux)"
        run: "cargo build --release --package anet-client --target x86_64-unknown-linux-gnu"

      - name: "Upload artifact"
        uses: "actions/upload-artifact@v4"
        with:
          name: "anet-client-linux"
          path: "target/x86_64-unknown-linux-gnu/release/anet-client"

  build-windows:
    runs-on: "windows-latest"
    steps:
      - uses: "actions/checkout@v4"

      - name: "Install Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"
          override: "true"

      - name: "Build (Windows MSVC)"
        run: "cargo build --release --package anet-client"

      - name: "Upload artifact"
        uses: "actions/upload-artifact@v4"
        with:
          name: "anet-client-windows.exe"
          path: "target/release/anet-client.exe"